version: '3'
services:
  server:
    image: santygo77/moniken:latest
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  ui:
    image: santygo77/moniken-ui:latest
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
        server:
            condition: service_started
        

networks:
  mynetwork:
    driver: bridge