server:
  port: 8080


spring:
  datasource:
    url: jdbc:h2:mem:moniken
  jpa:
    open-in-view: true
  h2:
    console:
      enabled: true

logging:
  level:
    root: off

springdoc:
  swagger-ui:
    operations-sorter: method