spring:
  main:
    log-startup-info: false
    banner-mode: off
  profiles:
    active: prod

  hateoas:
    use-hal-as-default-json-media-type: false

  # it's need for integrate HATEOAS with Jackson JsonView annotation
  jackson:
    mapper:
      default-view-inclusion: true
  h2:
    console:
      enabled: ${moniken.h2}
      path: ${moniken.endpoint}/h2-console

springdoc:
  api-docs:
    enabled: true
    path: ${moniken.endpoint}/api-docs
  swagger-ui:
    path: ${moniken.endpoint}/swagger-ui
    disable-swagger-default-url: true

moniken:
  endpoint: /moniken
  version: @project.version@
  welcome-console: true
  port: 8080
  h2: false

server:
  port: ${moniken.port}
