spring:
  main:
    log-startup-info: false
    banner-mode: off
  profiles:
    active: prod
  mvc:
    static-path-pattern: "${moniken.endpoint}/**"

  # it's need for integrate HATEOAS with Jackson JsonView annotation
  jackson:
    mapper:
      default-view-inclusion: true
  h2:
    console:
      enabled: false
      path: "${moniken.endpoint}/h2-console"

moniken:
  endpoint: "/moniken"
  version: @project.version@
  welcome-console: true
  port: 8080

server:
  port: ${moniken.port}
