spring:
  main:
    log-startup-info: false
    banner-mode: off
  profiles:
    active: prod

  h2:
    console:
      enabled: false
      path: "${moniken.endpoint}/h2-console"

moniken:
  endpoint: "/moniken"
  version: @project.version@
  port: 8080

server:
  port: ${moniken.port}
