name: Build & Test Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '.github/workflows/build-and-test-backend.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '.github/workflows/build-and-test-backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v3
    - 
      name: Set Up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: 'maven'
    - 
      name: Build
      run: mvn -B clean verify
      working-directory: ${{env.working-directory}}
    - 
      name: Test Report
      run: mvn -B test
      working-directory: ${{env.working-directory}}
