name: Build frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: 'moniken-ui'
    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest
